### ISSUE TITLE
Optional Cookie as object doesn't work with `aot: true`

### ISSUE THREAD

**Issue by bogeychan** [elysiajs/elysia#832]
### What version of Elysia is running?

1.1.13

### What platform is your computer?

WSL Ubuntu

### What steps can reproduce the bug?

```ts
import { Elysia, t } from "elysia";

new Elysia({ aot: true })
  .get(
    "/",
    ({ cookie: { profile } }) => {
      profile.value = {
        id: 617,
        name: "Summoning 101",
      };
    },
    {
      cookie: t.Cookie(
        {
          profile: t.Optional(
            t.Object({
              id: t.Numeric(),
              name: t.String(),
            })
          ),
        },
        {
          secrets: "Fischl von Luftschloss Narfidort",
          sign: ["profile"],
        }
      ),
    }
  )
  .listen(8080);
```

### What is the expected behavior?

no error

### What do you see instead?

```json
{"name":"TypeError","message":"Cookie value must be provided as a string."}
```

### Additional information

this works with `aot: false`

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yes

**Comment by SaltyAom** [comment]
Probably fixed with commit to resolve #833 or prior because I'm unable to reproduce on the latest version

**Comment by bogeychan** [comment]
Same issue on my end, using `bun@1.2.19` and `elysia@1.3.8`:

<img width="552" height="411" alt="Image" src="https://github.com/user-attachments/assets/546f9cb5-fb76-436f-88d2-51f2fafbbc1e" />

Same with https://github.com/elysiajs/elysia/issues/833 and https://github.com/elysiajs/elysia/issues/713, did you forgot to publish new version?

**Comment by bogeychan** [comment]
https://github.com/elysiajs/elysia/issues/832 and https://github.com/elysiajs/elysia/issues/833 works as espected on master branch, but https://github.com/elysiajs/elysia/issues/713 fails

**Comment by SaltyAom** [comment]
@bogeychan Right, I haven't published 1.3.9 yet but you can use `1.3.9-beta.0` which is tagged as `@next`

```bash
bun add elysia@1.3.9-beta.0
```

**Comment by SaltyAom** [comment]
I assume this was fixed 👉👈
Feel free to reopen the issue if it isn't

![Image](https://github.com/user-attachments/assets/e1a77532-5194-4580-8dd9-694af7756ada)
